# Site settings
title: Zac Kolton
description: Zac's Minimal Resume 
# baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zac Kolton
user_description: I'm a Computer Science Student from MB Canada, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Fin Tech working with Conquest Planning Inc., a Manitoba based startup trying to improve the world through financial planning. I'm (one of) the first student developer(s) they hired to work on the platform.
user_title: Student Developer
email: zac.kolton@hotmail.com
# twitter_username: lorem_ipsum
linkedin_username: zac-kolton
github_username:  zacKolton

exclude: ['package.json', 'src' , 'node_modules']
